# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sensor_pb2 as sensor__pb2


class SensorServiceGRPCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/com.sd.sensors.SensorServiceGRPC/Send',
        request_serializer=sensor__pb2.Command.SerializeToString,
        response_deserializer=sensor__pb2.Message.FromString,
        )


class SensorServiceGRPCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SensorServiceGRPCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=sensor__pb2.Command.FromString,
          response_serializer=sensor__pb2.Message.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.sd.sensors.SensorServiceGRPC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
