// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor.proto

package com.sd.sensors;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sd.sensors.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.sd.sensors.Sensor sensors = 1;</code>
   */
  java.util.List<com.sd.sensors.Sensor> 
      getSensorsList();
  /**
   * <code>repeated .com.sd.sensors.Sensor sensors = 1;</code>
   */
  com.sd.sensors.Sensor getSensors(int index);
  /**
   * <code>repeated .com.sd.sensors.Sensor sensors = 1;</code>
   */
  int getSensorsCount();
  /**
   * <code>repeated .com.sd.sensors.Sensor sensors = 1;</code>
   */
  java.util.List<? extends com.sd.sensors.SensorOrBuilder> 
      getSensorsOrBuilderList();
  /**
   * <code>repeated .com.sd.sensors.Sensor sensors = 1;</code>
   */
  com.sd.sensors.SensorOrBuilder getSensorsOrBuilder(
      int index);
}
